name: osm_imports_preparations
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - geopy
  - markdown >= 3.2.1
  - matplotlib
  - mkdocs
  - pandas
  - pip
  - pygments
  - spyder
  - spyder-notebook
  - python-wget
  - pip:
      - keras-autodoc
      - mkdocs-material
      - mknotebooks
      - mktheapidocs[plugin]

