name: osm_imports_preparations
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - mkdocs
  - pandas
  - pip
  - spyder
  - python-wget
  - pip:
      - keras-autodoc
      - mkdocs-material

